
services:
  - type: web
    name: gemini-tickets
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase: {
          name: gemini-tickets-db,
          property: connectionString
        }
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  - type: postgres
    name: gemini-tickets-db
    plan: free

  - type: redis
    name: gemini-tickets-redis
    plan: free
